"""docs/coverage.md from the corpus bench's results (corpus/run.py), and the regression check of the CI job.

    python corpus/coverage.py <work>/results.json [-o docs/coverage.md] [--baseline corpus/baseline.json]
                              [--update-baseline] [--only-sqlalchemy]

With --baseline, exits 1 when the share of identical examples (FastAPI, Pydantic or SQLAlchemy) is below the
baseline's, or when an example identical in the baseline is not any more. --update-baseline rewrites it.
--only-sqlalchemy reads the results of `corpus/sqlalchemy_docs.py` alone (<work>/sqla/results.json) and rewrites
only the SQLAlchemy section of the -o file (and only the SQLAlchemy entries of the baseline).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

STATUSES = ["identical", "documented", "differs", "refused", "error", "untested", "docs-only", "nondeterministic",
            "reference-fails"]
FASTAPI_DOCS = "https://fastapi.tiangolo.com/"
PYDANTIC_DOCS = "https://docs.pydantic.dev/2.13/"
SQLALCHEMY_DOCS = "https://docs.sqlalchemy.org/en/21/"
SQLA_START, SQLA_END = "<!-- sqlalchemy:start -->", "<!-- sqlalchemy:end -->"
TITLE = "# Coverage of the FastAPI, Pydantic and SQLAlchemy documentation"
SECTION_ORDER = ["Tutorial - User Guide", "Advanced User Guide", "How To - Recipes", "Other", "Pydantic"]


def scored(rs: list[dict]) -> list[dict]:
    """The examples the share is computed on: those an official test (or a recorded input) exercises over
    HTTP; `untested` and `docs-only` examples are listed apart."""
    return [r for r in rs if r["status"] not in ("untested", "docs-only", "nondeterministic", "reference-fails")
            and (r["kind"] in ("pydantic", "sqlalchemy") or r["tests"])]


def share(rs: list[dict]) -> float:
    s = scored(rs)
    return round(100 * sum(r["status"] in ("identical", "documented") for r in s) / len(s), 1) if s else 0.0


def page_url(r: dict) -> str:
    page = r["page"]
    if r["kind"] == "sqlalchemy":
        return SQLALCHEMY_DOCS + (f"orm/extensions/{Path(page).stem}.html" if page.endswith(".py") else
                                  page.removeprefix("doc/build/").removesuffix(".rst") + ".html")
    if r["kind"] == "pydantic":
        return PYDANTIC_DOCS + page.removeprefix("docs/").removesuffix(".md").removesuffix("index") + "/"
    return FASTAPI_DOCS + page.removesuffix(".md").removesuffix("index") + "/" if page else ""


def _one_line(text: str, n: int = 160) -> str:
    text = " ".join((text or "").split())
    return text if len(text) <= n else text[: n - 1] + "…"


def _diff(d: dict) -> str:
    ref, cand = d["ref"], d["cand"]
    fields = [k for k in dict.fromkeys(list(ref) + list(cand)) if k != "req" and ref.get(k) != cand.get(k)]
    shown = ", ".join(f"`{k}`" for k in fields[:4])
    return f"`{_one_line(ref.get('req', '?'), 70)}`: {shown or 'differs'}"


def render(data: dict) -> str:
    ex = data["examples"]
    sq = [r for r in ex.values() if r["kind"] == "sqlalchemy"]
    rs = [r for r in ex.values() if r["kind"] != "sqlalchemy"]
    fa = [r for r in rs if r["kind"] == "fastapi"]
    py = [r for r in rs if r["kind"] == "pydantic"]
    o = [TITLE, "",
         "<!-- Generated by corpus/coverage.py from a corpus/run.py run: do not edit by hand. -->", "",
         f"py2axum is measured on the examples of the official documentation: every app of FastAPI's `docs_src/` "
         f"(FastAPI {data['fastapi']}), replayed with FastAPI's own tests (`tests/test_tutorial/`) against the "
         f"Python reference and against the binary, and every Pydantic {data['pydantic']} documentation block that "
         "validates a model, served by a minimal FastAPI route around each model. Responses are compared as the "
         "[conformance harness](advanced/conformance.md) compares them: status, headers, body byte for byte, key order "
         "included. The SQLAlchemy documentation has [its own section](#sqlalchemy). The bench is in `corpus/` "
         "([how it works](https://github.com/larrymotalavigne/py2axum/blob/main/corpus/README.md)).", "",
         "| Status | Meaning |", "|---|---|",
         "| identical | every compared response is the same |",
         "| documented | the responses differ only by a [documented difference](supported.md) (the order of a `set`, an integer beyond 64 bits) |",
         "| differs | at least one response differs (a bug, unless listed in [supported.md](supported.md)) |",
         "| refused | py2axum refuses the example at translation, with the reason at file:line |",
         "| error | the translator crashed, or the generated code did not compile or start |",
         "| untested | translated, but no official test sends it a request |",
         "| docs-only | its tests only request `/openapi.json` or `/docs`, which the binary does not serve |",
         "| nondeterministic | Python's own responses vary from run to run (`random`): compared, never counted |",
         "| reference-fails | the Python reference itself fails (SQLAlchemy section only): listed, never counted |", "",
         "The OpenAPI schema and documentation pages are not served by the binary (see "
         "[supported.md](supported.md#not-supported)): those requests are sent to both servers but not compared. "
         "Requests a test sends while it sets `app.dependency_overrides` are not compared either (only the "
         "in-process app sees the override). A JWT in a body is compared claim by claim, its `exp`/`iat`/`nbf` "
         "within 2 seconds (the two servers are called one after the other). The share is that of the `identical` and `documented` examples among "
         "those a test exercises over HTTP (`untested`, `docs-only` and `nondeterministic` ones are counted "
         "apart).", "", "## Summary", "",
         "| Corpus | Examples | " + " | ".join(STATUSES) + " | Share |",
         "|---|" + "---:|" * (len(STATUSES) + 2)]
    for name, group in (("FastAPI", fa), ("Pydantic", py)):
        c = Counter(r["status"] for r in group)
        o.append(f"| {name} | {len(group)} | " + " | ".join(str(c.get(s, 0)) for s in STATUSES) +
                 f" | **{share(group)} %** |")
    t = data.get("timings", {})
    if t:
        o += ["", "Bench run: " + ", ".join(f"{k} {v} s" for k, v in t.items()) + "."]

    reasons = Counter()
    for r in rs:
        if r["status"] == "refused":
            for c in {x["construction"] for x in r.get("reasons", [])} or {r.get("reason", "?")}:
                reasons[c] += 1
    if reasons:
        o += ["", "## Most frequent refusals", "",
              "An example may be refused for several reasons; each is counted once per example.", "",
              "| Construction | Examples |", "|---|---:|"]
        o += [f"| {c} | {n} |" for c, n in reasons.most_common(25)]

    by_section: dict[str, dict[str, list]] = defaultdict(lambda: defaultdict(list))
    for r in rs:
        by_section[r["section"]][r["page"]].append(r)
    nav = {p: i for i, p in enumerate(data.get("nav", []))}
    for section in sorted(by_section, key=lambda s: SECTION_ORDER.index(s) if s in SECTION_ORDER else 99):
        pages = by_section[section]
        o += ["", f"## {section}", "", "| Page | Examples | identical | differs | refused | error | other | Share |",
              "|---|---:|---:|---:|---:|---:|---:|---:|"]
        order = sorted(pages, key=lambda p: (nav.get(p, 10**6), p))
        for p in order:
            group = pages[p]
            c = Counter(r["status"] for r in group)
            title = group[0]["title"] or p
            link = page_url(group[0])
            other = c.get("untested", 0) + c.get("docs-only", 0) + c.get("nondeterministic", 0)
            o.append(f"| [{title}]({link}) | {len(group)} | {c.get('identical', 0) + c.get('documented', 0)} | {c.get('differs', 0)} | "
                     f"{c.get('refused', 0)} | {c.get('error', 0)} | {other} | {share(group)} % |")
        details = []
        for p in order:
            bad = [r for r in pages[p] if r["status"] in ("refused", "differs", "error")]
            if not bad:
                continue
            details += ["", f"### {pages[p][0]['title'] or p}", ""]
            for r in sorted(bad, key=lambda r: r["source"]):
                if r["status"] == "refused":
                    why = r.get("reasons") or [{"construction": r.get("reason", "?"), "where": "", "error": ""}]
                    first = why[0]
                    more = f" (+{len(why) - 1} more)" if len(why) > 1 else ""
                    details.append(f"- `{r['source']}` — refused: {first['construction']} at `{first['where']}`{more}")
                elif r["status"] == "differs":
                    details.append(f"- `{r['source']}` — differs on {r['n_diffs']}/{r['compared']} responses: "
                                   + _diff(r["diffs"][0]))
                else:
                    details.append(f"- `{r['source']}` — error ({r.get('error_kind')}): "
                                   f"`{_one_line(r.get('error', ''), 140)}`")
        if details:
            o += ["", f"<details><summary>{section}: refused, differing and failing examples</summary>", *details, "",
                  "</details>"]
    o += ["", *render_sqlalchemy(data, sq)]
    return "\n".join(o) + "\n"


def render_sqlalchemy(data: dict, sq: list[dict]) -> list[str]:
    """The SQLAlchemy section, between markers (--only-sqlalchemy rewrites it alone)."""
    if not sq:
        return []
    o = [SQLA_START, "## SQLAlchemy", "",
         f"The SQLAlchemy {data.get('sqlalchemy', '')} documentation is run as SQLAlchemy runs it, as doctests "
         "(the units of `test/base/test_tutorials.py`: the Unified Tutorial, the ORM Quick Start, the ORM Querying "
         "Guide, large collections, asyncio; then other ORM, extension and Core pages, as written). Each code block "
         "that executes SQL is an example: a minimal FastAPI route runs it, preceded by the earlier statements of the "
         "page it depends on, in a session of its own, and returns what the block prints and displays. A block that "
         "only shows a `SELECT` for its SQL text is executed too (rows returned). Each route exists twice: `sync` "
         "(a `Session` dependency) and `async` (an `AsyncSession` with `expire_on_commit=False`, `await` on its "
         "methods). PostgreSQL, the database put back to the page's seed data before every request; the Python "
         "reference and the binary are compared as above. `reference-fails`: the Python reference fails on the "
         "route (mostly a lazy load under `AsyncSession`, which raises `MissingGreenlet`).", "",
         "| Variant | Examples | " + " | ".join(STATUSES) + " | Share |",
         "|---|" + "---:|" * (len(STATUSES) + 2)]
    for name, group in (("sync", [r for r in sq if r.get("variant") == "sync"]),
                        ("async", [r for r in sq if r.get("variant") == "async"]), ("**SQLAlchemy**", sq)):
        c = Counter(r["status"] for r in group)
        o.append(f"| {name} | {len(group)} | " + " | ".join(str(c.get(s, 0)) for s in STATUSES) +
                 f" | **{share(group)} %** |")
    skipped = data.get("sqlalchemy_skipped") or {}
    if skipped:
        o += ["", f"Not in the corpus: {sum(skipped.values())} examples (both variants) the bench cannot run as "
              "written: " + ", ".join(f"{k} ({n})" for k, n in sorted(skipped.items(), key=lambda kv: -kv[1]))
              + " (SQLite-only SQL, a statement of the page that fails before them)."]
    reasons = Counter()
    for r in sq:
        if r["status"] == "refused":
            for c in {x["construction"] for x in r.get("reasons", [])} or {r.get("reason", "?")}:
                reasons[c] += 1
    if reasons:
        o += ["", "### SQLAlchemy: most frequent refusals", "", "| Construction | Examples |", "|---|---:|"]
        o += [f"| {_one_line(c, 120)} | {n} |" for c, n in reasons.most_common(25)]
    pages: dict[str, list[dict]] = defaultdict(list)
    for r in sq:
        pages[r["page"]].append(r)
    o += ["", "### SQLAlchemy: per page", "",
          "| Page | Section | Blocks | identical | differs | refused | error | other | sync | async | Share |",
          "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    order = list(dict.fromkeys(r["page"] for r in sq))
    for p in order:
        g = pages[p]
        c = Counter(r["status"] for r in g)
        other = sum(c.get(k, 0) for k in ("untested", "docs-only", "nondeterministic", "reference-fails"))
        blocks = len({r["source"] for r in g})
        o.append(f"| [{g[0]['title']}]({page_url(g[0])}) | {g[0]['section']} | {blocks} | "
                 f"{c.get('identical', 0) + c.get('documented', 0)} | {c.get('differs', 0)} | {c.get('refused', 0)} | "
                 f"{c.get('error', 0)} | {other} | {share([r for r in g if r.get('variant') == 'sync'])} % | "
                 f"{share([r for r in g if r.get('variant') == 'async'])} % | {share(g)} % |")
    details = []
    for p in order:
        bad = [r for r in pages[p] if r["status"] in ("refused", "differs", "error", "reference-fails")]
        if not bad:
            continue
        details += ["", f"#### {pages[p][0]['title']} (`{p}`)", ""]
        for r in sorted(bad, key=lambda r: (int(r["source"].rsplit(":", 1)[1]), r.get("variant", ""))):
            head = f"- `{r['source']}` {r.get('variant', '')}"
            if r["status"] == "refused":
                why = r.get("reasons") or [{"construction": r.get("reason", "?"), "where": "", "error": ""}]
                more = f" (+{len(why) - 1} more)" if len(why) > 1 else ""
                details.append(f"{head} — refused: {_one_line(why[0]['construction'], 100)} at `{why[0]['where']}`{more}")
            elif r["status"] == "differs":
                details.append(f"{head} — differs: " + _diff(r["diffs"][0]))
            elif r["status"] == "reference-fails":
                details.append(f"{head} — the Python reference fails: `{_one_line(r.get('error', ''), 140)}`")
            else:
                details.append(f"{head} — error ({r.get('error_kind')}): `{_one_line(r.get('error', ''), 140)}`")
    if details:
        o += ["", "<details><summary>SQLAlchemy: refused, differing and failing examples</summary>", *details, "",
              "</details>"]
    return o + [SQLA_END]


def baseline_of(data: dict) -> dict:
    rs = list(data["examples"].values())
    out = {"fastapi_share": share([r for r in rs if r["kind"] == "fastapi"]),
           "pydantic_share": share([r for r in rs if r["kind"] == "pydantic"]),
           "sqlalchemy_share": share([r for r in rs if r["kind"] == "sqlalchemy"]),
           "identical": sorted(k for k, r in data["examples"].items() if r["status"] in ("identical", "documented"))}
    for kind in ("fastapi", "pydantic", "sqlalchemy"):
        if not any(r["kind"] == kind for r in rs):
            del out[f"{kind}_share"]
    return out


def regressions(data: dict, base: dict) -> list[str]:
    now = baseline_of(data)
    out = []
    for k in ("fastapi_share", "pydantic_share", "sqlalchemy_share"):
        if k in now and now[k] < base.get(k, 0):
            out.append(f"{k}: {now[k]} % < baseline {base[k]} %")
    lost = sorted(set(base.get("identical", [])) - set(now["identical"]) & set(data["examples"]))
    out += [f"{i}: identical in the baseline, now {data['examples'][i]['status']}" for i in lost]
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("results", type=Path)
    ap.add_argument("-o", "--out", type=Path, default=None)
    ap.add_argument("--baseline", type=Path, default=None)
    ap.add_argument("--update-baseline", action="store_true")
    ap.add_argument("--only-sqlalchemy", action="store_true", help="results of corpus/sqlalchemy_docs.py alone")
    args = ap.parse_args()
    data = json.loads(args.results.read_text())
    if args.only_sqlalchemy:
        data = {"sqlalchemy": data["version"], "sqlalchemy_skipped": data.get("skipped", {}),
                "examples": data["examples"]}
    if args.out and args.only_sqlalchemy:
        text = args.out.read_text() if args.out.exists() else TITLE + "\n"
        block = "\n".join(render_sqlalchemy(data, list(data["examples"].values())))
        if SQLA_START in text:
            text = text[:text.index(SQLA_START)] + block + text[text.index(SQLA_END) + len(SQLA_END):]
        else:
            text = text.rstrip("\n") + "\n\n" + block + "\n"
        args.out.write_text(re.sub(r"\A# [^\n]*", TITLE, text))
    elif args.out:
        args.out.write_text(render(data))
    rc = 0
    if args.baseline and args.update_baseline:
        new = baseline_of(data)
        if args.only_sqlalchemy and args.baseline.exists():
            old = json.loads(args.baseline.read_text())
            keep = [k for k in old.get("identical", []) if not k.startswith("sqla_")]
            new = {**old, "sqlalchemy_share": new["sqlalchemy_share"],
                   "identical": sorted(keep + [k for k in new["identical"] if k.startswith("sqla_")])}
        args.baseline.write_text(json.dumps(new, indent=1) + "\n")
    elif args.baseline and args.baseline.exists():
        bad = regressions(data, json.loads(args.baseline.read_text()))
        for b in bad:
            print(f"regression: {b}", file=sys.stderr)
        rc = 1 if bad else 0
    b = baseline_of(data)
    print(", ".join(f"{k.split('_')[0]} {v} % identical" for k, v in b.items() if k.endswith("_share")), file=sys.stderr)
    return rc


if __name__ == "__main__":
    sys.exit(main())
