"""MkDocs hooks of the documentation site (mkdocs.yml `hooks:`).

- the version of the package documented (pyproject.toml), in the footer and wherever a page writes
  `<!-- py2axum:version -->`;
- the reference of the command line, from the real `--help` (`<!-- py2axum:cli-help -->`,
  `<!-- py2axum:check-help -->`): py2axum has no dependency, it runs from the checkout;
- coverage.md: written by the corpus bench; until it exists, a placeholder page keeps its place in the nav.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

from mkdocs.structure.files import File

ROOT = Path(__file__).resolve().parents[2]
VERSION = re.search(r'^version = "([^"]+)"', (ROOT / "pyproject.toml").read_text(), re.M).group(1)

COVERAGE_PLACEHOLDER = """# Coverage

This page will hold the coverage table of the official corpus: the example applications of FastAPI's
documentation and the examples of Pydantic's, translated by py2axum and replayed against the binary, page by
page of their documentation: identical to Python, left to Python, or refused with `file:line`.

It is generated by the corpus bench and is not published yet. Until then, `py2axum check` gives the same
verdict for your own application, route by route: see [py2axum check](getting-started/check.md).
"""


def _help(*args: str) -> str:
    env = {**os.environ, "PYTHONPATH": str(ROOT), "COLUMNS": "100"}
    out = subprocess.run([sys.executable, "-m", "py2axum", *args, "--help"], cwd=ROOT, env=env,
                         capture_output=True, text=True, check=True).stdout
    return f"```text\n{out.rstrip()}\n```"


def on_config(config, **kwargs):
    config.copyright = f"py2axum {VERSION} · Apache License 2.0"
    config.extra["py2axum_version"] = VERSION
    return config


def on_files(files, config, **kwargs):
    if files.get_file_from_path("coverage.md") is None:
        files.append(File.generated(config, "coverage.md", content=COVERAGE_PLACEHOLDER))
    return files


def on_page_markdown(markdown: str, page, config, files, **kwargs) -> str:
    markdown = markdown.replace("<!-- py2axum:version -->", VERSION)
    if "<!-- py2axum:cli-help -->" in markdown:
        markdown = markdown.replace("<!-- py2axum:cli-help -->", _help())
    if "<!-- py2axum:check-help -->" in markdown:
        markdown = markdown.replace("<!-- py2axum:check-help -->", _help("check"))
    return markdown
