"""Back-end: IR -> Rust/axum project on disk."""
from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

from . import body as B
from .ir import MISSING, App, OrmModel, Param, Route, Schema, SchemaField, TranspileError, TypeRef

RUNTIME = Path(__file__).parent / "runtime" / "rt.rs"

CARGO_TOML = """\
[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

# Generated by py2axum from {source}. Do not edit by hand: change the Python and regenerate.

[dependencies]
axum = "0.8"
tokio = {{ version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time", "signal"] }}
futures-util = "0.3"
sqlx = {{ version = "0.8", default-features = false, features = ["runtime-tokio", "postgres", "macros"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = {{ version = "1", features = ["preserve_order"] }}
reqwest = {{ version = "0.12", default-features = false, features = ["json", "rustls-tls"] }}
form_urlencoded = "1"
regex = "1"
tower = {{ version = "0.5", features = ["util"] }}
{extra_deps}
[profile.release]
lto = "fat"
codegen-units = 1
"""


def rs_str(s: str) -> str:
    return json.dumps(s)


# ====================================================================== types


def field_rust_type(t: TypeRef) -> str:
    if t.kind == "optional":
        return f"Option<{field_rust_type(t.inner)}>"
    if t.kind == "list":
        return f"Vec<{field_rust_type(t.inner)}>"
    if t.kind == "schema":
        return t.name
    return {"int": "i64", "str": "String", "bool": "bool", "float": "f64", "json": "serde_json::Value"}[t.kind]


def literal_for(value, t: TypeRef) -> str:
    if value is None:
        return "None"
    base = t.base()
    if base.kind == "bool":
        lit = "true" if value else "false"
    elif base.kind == "int":
        lit = f"{int(value)}i64"
    elif base.kind == "float":
        lit = f"{float(value)!r}f64"
    elif base.kind == "str":
        lit = f"{rs_str(value)}.to_string()"
    elif base.kind == "list" and value == []:
        lit = "Vec::new()"
    else:
        raise TranspileError(f"unsupported default value {value!r}")
    return f"Some({lit})" if t.is_optional else lit


def checks(cons: dict, base_kind: str) -> str:
    """Parse + constraint expression applied to `x` (a &Value) with a `loc` expression."""
    parts = []
    for k, ctor in (("ge", "Ge"), ("gt", "Gt"), ("le", "Le"), ("lt", "Lt")):
        if k in cons:
            parts.append(f"rt::NumCheck::{ctor}({float(cons[k])!r})")
    return ", ".join(parts)


def scalar_parse(t: TypeRef, cons: dict, x: str, loc: str) -> str:
    """Rust expression `Option<T>` parsing JSON value `x` (by ref) into base scalar type `t`."""
    k = t.kind
    if k == "str":
        expr = f"rt::v_str({x}, {loc}, errs)"
        if "min_length" in cons or "max_length" in cons:
            mn = f"Some({cons['min_length']})" if "min_length" in cons else "None"
            mx = f"Some({cons['max_length']})" if "max_length" in cons else "None"
            expr += f".and_then(|s| rt::c_str_len(s, {mn}, {mx}, {loc}, {x}, errs))"
        return expr
    if k == "int":
        expr = f"rt::v_int({x}, {loc}, errs)"
        c = checks(cons, k)
        if c:
            expr += f".and_then(|n| rt::c_int(n, &[{c}], {loc}, {x}, errs))"
        return expr
    if k == "float":
        expr = f"rt::v_float({x}, {loc}, errs)"
        c = checks(cons, k)
        if c:
            expr += f".and_then(|n| rt::c_num(n, &[{c}], {loc}, {x}, errs))"
        return expr
    if k == "bool":
        return f"rt::v_bool({x}, {loc}, errs)"
    if k == "json":
        return f"Some({x}.clone())"
    raise TranspileError(f"unsupported field type {k}")


# ====================================================================== models


def gen_models(app: App) -> str:
    out = [
        "// Generated by py2axum from the SQLAlchemy models. Do not edit.",
        "#![allow(dead_code)]",
        "",
    ]
    ddl = []
    for m in app.models.values():
        out.append("#[derive(Debug, Clone, sqlx::FromRow)]")
        out.append(f"pub struct {m.name} {{")
        for c in m.columns:
            out.append(f"    pub {B.rust_ident(c.name)}: {c.rust_type},")
        out.append("}")
        out.append("")
        cols = []
        for c in m.columns:
            cols.append(f"{c.name} {c.sql_type}{'' if c.nullable else ' NOT NULL'}")
        cols.append(f"PRIMARY KEY ({m.pk.name})")
        cols += [f"UNIQUE ({c.name})" for c in m.columns if c.unique]
        ddl.append(f"CREATE TABLE IF NOT EXISTS {m.table} ({', '.join(cols)})")
    out.append("/// Same DDL as SQLAlchemy's `Base.metadata.create_all`.")
    out.append("pub const CREATE_TABLES: &[&str] = &[")
    out += [f"    {rs_str(d)}," for d in ddl]
    out.append("];")
    return "\n".join(out) + "\n"


# ====================================================================== schemas


def gen_schemas(app: App, conversions: set[str]) -> str:
    out = [
        "// Generated by py2axum from the Pydantic schemas. Do not edit.",
        "#![allow(dead_code, unused_mut, clippy::all)]",
        "use crate::{models, rt};",
        "use serde::Serialize;",
        "use serde_json::Value;",
        "",
    ]
    for s in app.schemas.values():
        out += gen_schema(s)
    for conv in sorted(conversions):
        sname, mname = conv.split(":")
        out += gen_from(app.schemas[sname], app.models[mname])
    return "\n".join(out) + "\n"


def gen_schema(s: Schema) -> list[str]:
    if len(s.fields) > 64:
        raise TranspileError(f"schema {s.name}: more than 64 fields")
    o = ["#[derive(Debug, Clone, Serialize)]", f"pub struct {s.name} {{"]
    for f in s.fields:
        rename = f'    #[serde(rename = {rs_str(f.name)})]' if B.rust_ident(f.name) != f.name else None
        if rename:
            o.append(rename)
        o.append(f"    pub {B.rust_ident(f.name)}: {field_rust_type(f.typ)},")
    o.append("    /// Pydantic `model_fields_set`, one bit per field.")
    o.append("    #[serde(skip)]")
    o.append("    pub fields_set_: u64,")
    o.append("}")
    o.append("")
    o.append(f"impl {s.name} {{")
    o.append("    pub fn is_set(&self, i: u32) -> bool {")
    o.append("        self.fields_set_ & (1u64 << i) != 0")
    o.append("    }")
    o.append("")
    o.append("    /// Validation with Pydantic v2 semantics (lax mode) and error shapes.")
    o.append("    pub fn from_json(v: &Value, prefix: &[&'static str], errs: &mut Vec<rt::ErrDetail>) -> Option<Self> {")
    o.append("        let loc_self: Vec<Value> = prefix.iter().map(|s| Value::from(*s)).collect();")
    o.append("        let obj = rt::expect_object(v, loc_self, errs)?;")
    o.append("        let start = errs.len();")
    o.append("        let mut fields_set_ = 0u64;")
    for i, f in enumerate(s.fields):
        o += [("        " + line) for line in field_parse(i, f)]
    o.append("        if errs.len() > start {")
    o.append("            return None;")
    o.append("        }")
    o.append("        Some(Self {")
    for f in s.fields:
        o.append(f"            {B.rust_ident(f.name)}: {B.rust_ident(f.name)}.unwrap(),")
    o.append("            fields_set_,")
    o.append("        })")
    o.append("    }")
    o.append("}")
    o.append("")
    return o


def field_parse(i: int, f: SchemaField) -> list[str]:
    name = B.rust_ident(f.name)
    loc = f"rt::loc(prefix, {rs_str(f.name)})"
    t = f.typ
    base = t.base()
    if base.kind == "schema":
        inner = (
            f"{{ let p: Vec<&'static str> = prefix.iter().copied().chain([{rs_str(f.name)}]).collect(); "
            f"{base.name}::from_json(x, &p, errs) }}"
        )
    elif base.kind == "list":
        item = base.inner
        if item.kind not in {"int", "str", "bool", "float"}:
            raise TranspileError(f"field {f.name}: only lists of scalars are supported")
        item_loc = f"{{ let mut l = {loc}; l.push(Value::from(j)); l }}"
        inner = (
            f"match x.as_array() {{ Some(a) => {{ let before = errs.len(); "
            f"let items: Vec<_> = a.iter().enumerate().filter_map(|(j, it)| {scalar_parse(item, f.constraints, 'it', item_loc)}).collect(); "
            f"if errs.len() > before {{ None }} else {{ Some(items) }} }}, "
            f'None => {{ errs.push(rt::ErrDetail {{ kind: "list_type", loc: {loc}, msg: "Input should be a valid list".into(), input: x.clone(), ctx: None }}); None }} }}'
        )
    else:
        inner = scalar_parse(base, f.constraints, "x", loc)
    lines = [f"let {name} = match obj.get({rs_str(f.name)}) {{"]
    if f.default is MISSING:
        lines.append(f"    None => {{ rt::missing(errs, {loc}, v); None }}")
    else:
        lines.append(f"    None => Some({literal_for(f.default, t)}),")
    if t.is_optional:
        lines.append(f"    Some(Value::Null) => {{ fields_set_ |= 1u64 << {i}; Some(None) }}")
        lines.append(f"    Some(x) => {{ fields_set_ |= 1u64 << {i}; ({inner}).map(Some) }}")
    else:
        lines.append(f"    Some(x) => {{ fields_set_ |= 1u64 << {i}; {inner} }}")
    lines.append("};")
    return lines


def gen_from(s: Schema, m: OrmModel) -> list[str]:
    """`ConfigDict(from_attributes=True)`: build the response schema from an ORM row."""
    o = [f"impl From<models::{m.name}> for {s.name} {{", f"    fn from(m: models::{m.name}) -> Self {{", "        Self {"]
    for f in s.fields:
        col = m.col(f.name)
        dst = field_rust_type(f.typ)
        if col is None:
            if f.default is MISSING:
                raise TranspileError(f"{s.name}.{f.name} has no column on {m.name} and no default")
            o.append(f"            {B.rust_ident(f.name)}: {literal_for(f.default, f.typ)},")
            continue
        src = col.rust_type
        place = f"m.{B.rust_ident(col.name)}"
        if src == dst:
            val = place
        elif src == "i32" and dst == "i64":
            val = f"i64::from({place})"
        elif src == "Option<i32>" and dst == "Option<i64>":
            val = f"{place}.map(i64::from)"
        elif dst == f"Option<{src}>":
            val = f"Some({place})"
        elif src == "i32" and dst == "Option<i64>":
            val = f"Some(i64::from({place}))"
        else:
            raise TranspileError(f"{s.name}.{f.name} ({dst}) is not compatible with {m.name}.{col.name} ({src})")
        o.append(f"            {B.rust_ident(f.name)}: {val},")
    o.append("            fields_set_: u64::MAX,")
    o.append("        }")
    o.append("    }")
    o.append("}")
    o.append("")
    return o


# ====================================================================== handlers


def gen_param(p: Param) -> list[str]:
    name = B.rust_ident(p.name)
    getter = f'rt::path_get(&__path, {rs_str(p.name)})' if p.source == "path" else f"__qm.get({rs_str(p.name)})"
    loc = f'rt::loc(&[{rs_str(p.source)}], {rs_str(p.name)})'
    t = p.typ
    parse = scalar_parse(t.base(), p.constraints, "&x", loc)
    lines = [f"let {name} = match {getter} {{"]
    if p.default is MISSING and not t.is_optional:
        lines.append(f"    None => {{ rt::missing(errs, {loc}, &serde_json::Value::Null); None }}")
    else:
        default = None if p.default is MISSING else p.default
        lines.append(f"    None => Some({literal_for(default, t)}),")
    if t.is_optional:
        lines.append(f"    Some(x) => ({parse}).map(Some),")
    else:
        lines.append(f"    Some(x) => {parse},")
    lines.append("};")
    return lines


def gen_handler(app: App, route: Route, conversions: set[str], stream: bool = True) -> list[str]:
    ctx = B.Ctx(app=app, route=route, stream=stream)
    has_path = any(p.source == "path" for p in route.params)
    has_query = any(p.source == "query" for p in route.params)
    body_p = next((p for p in route.params if p.source == "body"), None)
    args = ["State(st): State<AppState>"]
    if has_path:
        args.append("__path: RawPathParams")
    if has_query:
        args.append("RawQuery(__query): RawQuery")
    if body_p:
        args.append("__body: Bytes")
    o = [
        f"/// {route.method.upper()} {route.path}  (from {Path(route.file).name}:{route.node.lineno} `{route.func}`)",
        f"pub async fn {route.rust_name}({', '.join(args)}) -> Result<Response, AppError> {{",
    ]
    inputs = [p for p in route.params if p.source in {"path", "query", "body"}]
    if inputs:
        o.append("    let mut __errs: Vec<rt::ErrDetail> = Vec::new();")
        o.append("    let errs = &mut __errs;")
    if has_query:
        o.append("    let __qm = rt::QueryMap::parse(__query.as_deref());")
    # FastAPI validates path params, then query params, then the body.
    for p in sorted(inputs, key=lambda p: {"path": 0, "query": 1, "body": 2}[p.source]):
        if p.source == "body":
            if p.typ.base().kind != "schema" or p.typ.is_optional:
                raise TranspileError(f"{route.func}: the body parameter must be a (non-optional) Pydantic model")
            o.append(
                f"    let {B.rust_ident(p.name)} = rt::parse_body(&__body, errs)"
                f'.and_then(|v| schemas::{p.typ.name}::from_json(&v, &["body"], errs));'
            )
        else:
            o += ["    " + line for line in gen_param(p)]
    if inputs:
        o.append("    if !__errs.is_empty() {")
        o.append("        return Err(AppError::Validation(__errs));")
        o.append("    }")
    for p in inputs:
        o.append(f"    let {B.rust_ident(p.name)} = {B.rust_ident(p.name)}.unwrap();")
        t = B.T("schema", p.typ.name) if p.source == "body" else B.typeref_to_t(p.typ)
        ctx.vars[p.name] = B.Var(B.rust_ident(p.name), t)
    lines = B.translate_route(ctx)
    o += lines
    o.append("}")
    o.append("")
    conversions |= ctx.uses
    return o


def gen_handlers(app: App, conversions: set[str], stream: bool = True) -> str:
    out = [
        "// Generated by py2axum from the FastAPI routes. Do not edit.",
        "#![allow(unused_mut, unused_variables, unused_imports, unreachable_code, dead_code, non_snake_case, clippy::all)]",
        "use crate::rt::{self, AppError};",
        "use crate::{models, schemas, AppState};",
        "use axum::body::Bytes;",
        "use axum::extract::{RawPathParams, RawQuery, State};",
        "use axum::response::Response;",
        "use std::sync::LazyLock;",
        "",
    ]
    for c in app.consts.values():
        if c.env:
            init = f"std::env::var({rs_str(c.env)}).unwrap_or_else(|_| {rs_str(c.default)}.to_string())"
        else:
            init = f"{rs_str(c.default)}.to_string()"
        out.append(f"pub static {c.name}: LazyLock<String> = LazyLock::new(|| {init});")
    out.append("")
    errors = []
    for r in app.routes:
        try:
            out += gen_handler(app, r, conversions, stream)
        except TranspileError as e:
            errors.append(e)
    if errors:
        raise TranspileErrors(errors)
    return "\n".join(out) + "\n"


class TranspileErrors(Exception):
    def __init__(self, errors: list[TranspileError]):
        self.errors = errors
        super().__init__("\n".join(e.render() for e in errors))


def gen_layers(app: App) -> tuple[str, str]:
    """(use lines, router layer lines) for the translated middleware."""
    if app.gzip is None:
        return "", ""
    g = app.gzip
    uses = (
        "use tower_http::compression::predicate::{NotForContentType, Predicate, SizeAbove};\n"
        "use tower_http::compression::{CompressionLayer, CompressionLevel};\n"
    )
    layer = (
        "        // app.add_middleware(GZipMiddleware, "
        f"minimum_size={g.minimum_size}, compresslevel={g.compresslevel})\n"
        "        .layer(\n"
        "            CompressionLayer::new()\n"
        f"                .quality(CompressionLevel::Precise({g.compresslevel}))\n"
        "                .compress_when(\n"
        f"                    SizeAbove::new({g.minimum_size})\n"
        "                        .and(NotForContentType::GRPC)\n"
        "                        .and(NotForContentType::IMAGES)\n"
        "                        .and(NotForContentType::SSE),\n"
        "                ),\n"
        "        )\n"
        "        .layer(axum::middleware::map_response(rt::starlette_vary))\n"
    )
    return uses, layer


def gen_main(app: App) -> str:
    from .dyn import starlette_pattern

    # Starlette's routing (declaration order, first full match, 405 from the first path match, slash
    # redirect): each route is its own one-route axum Router, picked by rt::dispatch
    route_lines = []
    for r in app.routes:
        pattern = starlette_pattern(r.path, None, "")
        route_lines.append(
            f"        ({rs_str(r.method.upper())}, regex::Regex::new({rs_str(pattern)}).unwrap(), "
            f"Router::new().route({rs_str(r.path)}, {r.method}(handlers::{r.rust_name})).with_state(state.clone())),"
        )
    methods = sorted({r.method for r in app.routes})
    layer_uses, layers = gen_layers(app)
    return f"""// Generated by py2axum. Do not edit.
mod handlers;
mod models;
mod rt;
mod schemas;

use axum::routing::{{{", ".join(methods)}}};
use axum::Router;
use sqlx::postgres::PgPoolOptions;
{layer_uses}
#[derive(Clone)]
pub struct AppState {{
    pub pool: sqlx::PgPool,
    pub http: reqwest::Client,
}}

fn env_or(key: &str, default: &str) -> String {{
    std::env::var(key).unwrap_or_else(|_| default.to_string())
}}

#[tokio::main]
async fn main() {{
    let database_url = env_or("DATABASE_URL", "postgresql://postgres@127.0.0.1/poc");
    let pool_size: u32 = env_or("DB_POOL_SIZE", "32").parse().expect("DB_POOL_SIZE");
    let pool = PgPoolOptions::new()
        .max_connections(pool_size)
        .connect(&database_url)
        .await
        .expect("cannot connect to the database");
    for ddl in models::CREATE_TABLES {{
        sqlx::query(ddl).execute(&pool).await.expect("create tables");
    }}
    let state = AppState {{ pool: pool.clone(), http: reqwest::Client::new() }};

    let table: std::sync::Arc<Vec<(&'static str, regex::Regex, Router)>> = std::sync::Arc::new(vec![
{chr(10).join(route_lines)}
    ]);
    let app = Router::new()
        .fallback(move |req: axum::extract::Request| rt::dispatch(table.clone(), req))
        // Starlette reads bodies of any size: lift axum's 2 MB default (413 otherwise)
        .layer(axum::extract::DefaultBodyLimit::disable())
{layers}        ;

    let addr = format!("{{}}:{{}}", env_or("HOST", "0.0.0.0"), env_or("PORT", "8080"));
    let listener = tokio::net::TcpListener::bind(&addr).await.expect("bind");
    eprintln!("listening on http://{{addr}}");
    // SIGTERM/SIGINT as uvicorn: no new connection, in-flight requests finished (bounded), pool closed
    tokio::select! {{
        r = axum::serve(listener, app).with_graceful_shutdown(rt::shutdown_signal()) => r.expect("server"),
        _ = rt::shutdown_deadline() => {{}}
    }}
    rt::exit_after_shutdown(&pool).await
}}
"""


# ====================================================================== project


def generate(app: App, out_dir: Path, source: str, crate_name: str, stream: bool = True) -> None:
    conversions: set[str] = set()
    handlers = gen_handlers(app, conversions, stream)  # first: collects the schema<-model conversions
    extra = 'tower-http = { version = "0.6", features = ["compression-gzip"] }\n' if app.gzip else ""
    files = {
        "Cargo.toml": CARGO_TOML.format(name=crate_name, source=source, extra_deps=extra),
        "src/main.rs": gen_main(app),
        "src/models.rs": gen_models(app),
        "src/schemas.rs": gen_schemas(app, conversions),
        "src/handlers.rs": handlers,
    }
    (out_dir / "src").mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        (out_dir / rel).write_text(content)
    shutil.copy(RUNTIME, out_dir / "src" / "rt.rs")
    if shutil.which("rustfmt"):
        subprocess.run(["rustfmt", "--edition", "2021", *map(str, (out_dir / "src").glob("*.rs"))], check=False)
